version: "3.7"

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx_tws_back
    image: nginx
    restart: always
    ports:
      - '707:707'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app

  database:
    image: mysql:8.0.33
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: interior
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 20s
      retries: 10
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - server-connection

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: twj_spring
    restart: on-failure
    expose:
      - "7070"
    depends_on:
      - database
    command: ./gradlew bootRun
    environment:
      - FRONT_ORIGIN_URL=${FRONT_ORIGIN_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - server-connection
    volumes:
      - ./interiorAppLogs:/logs