version: "3.7"
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: interior
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3309:3306"
    restart: unless-stopped
  app: #4
    build: #5
      context: ./app
      dockerfile: Dockerfile
      container_name: twj_spring
      links: #6
        - db
      restart: always
      ports:
        - "80:8080"
      depends_on: #7
        - db
      environment: #8
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3309/interior?characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 1234567