version: "3.7"
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: interior
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3309:3306"
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
      - "80:80"