server:
  port: 7070
  front:
    origin-url: ${FRONT_ORIGIN_URL}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
  datasource:
    url: jdbc:mysql://database:3306/interior?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://database:3306/interior?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    com.interior.InteriorApplication: debug, info
    com.interior.adapter.inbound.user: debug, info
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: /app/logs/server-%d{yyyy-MM-dd}.log
  file:
    name: /app/logs/server.log
  appenders:
    file:
      type: ch.qos.logback.core.FileAppender
      file: ${logging.file.name}
      encoder:
        pattern: ${logging.pattern.file}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health

jwt:
  secret-key: ${JWT_SECRET_KEY}
