server:
  port: 7070
  front:
    origin-url: ${FRONT_ORIGIN_URL}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
  datasource:
    url: jdbc:mysql://database:3306/interior?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://database:3306/interior?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health

jwt:
  secret-key: ${JWT_SECRET_KEY}
