name: Java CI/CD with Gradle

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: execute remote ssh & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            response=$(curl -s http://localhost:7070/actuator/health)ctuator/health)
            if [[ "$response" == *"\"status\":\"UP\""* ]]; then
              echo "true"
            else
              failure()
            fi
