name: Java CI/CD with Gradle

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: execute remote ssh & deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          whoami
          cd /home/twj/interior
          git pull
          ./gradlew build
          cd /home/twj/interior/build/libs
          nohup java -jar interior-0.0.1-SNAPSHOT.jar &
          echo -ne '\n' | command
          curl http://localhost:${{ secrets.BACKEND_PORT }}/actuator/health
