name: PR_CI

on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: openjdk:17  # Use an appropriate Docker image with JDK 17 pre-installed

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - name: Run CI checks with Gradle Wrapper
        run: ./gradlew check