name: PR_CI

on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run CI test with Gradle Wrapper
        run: ./gradlew test

      - name: Verify Docker
        run: docker ps