name: PR_CI

on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: openjdk:17

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        run: |
          apt-get update
          apt-get install -y openjdk-17-jdk

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - name: Run CI checks with Gradle Wrapper
        run: ./gradlew check

      - name: Run CI checks with Gradle Wrapper
        run: ./gradlew check